import { defineConfig } from 'tsup';
export default defineConfig({
  entry: {
    vite: 'src/vite.ts',
    client: 'src/client.ts',
    browser: 'src/browser.ts',
    host: 'src/host.ts',
    worker: 'src/worker.ts',
    'runtime/assert-strict': 'src/runtime/assert-strict.ts',
    'runtime/child-process': 'src/runtime/child-process.ts',
    'runtime/fs': 'src/runtime/fs.ts',
    'runtime/fs-promises': 'src/runtime/fs-promises.ts',
    'runtime/filesystem': 'src/runtime/filesystem.ts',
    'runtime/http': 'src/runtime/http.ts',
    'runtime/http2': 'src/runtime/http2.ts',
    'runtime/https': 'src/runtime/https.ts',
    'runtime/module': 'src/runtime/module.ts',
    'runtime/net': 'src/runtime/net.ts',
    'runtime/path': 'src/runtime/path.ts',
    'runtime/os': 'src/runtime/os.ts',
    'runtime/perf-hooks': 'src/runtime/perf-hooks.ts',
    'runtime/process': 'src/runtime/process.ts',
    'runtime/stream-promises': 'src/runtime/stream-promises.ts',
    'runtime/timers': 'src/runtime/timers.ts',
    'runtime/tls': 'src/runtime/tls.ts',
    'runtime/tty': 'src/runtime/tty.ts',
    'runtime/url': 'src/runtime/url.ts',
    'runtime/util': 'src/runtime/util.ts',
    'runtime/v8': 'src/runtime/v8.ts',
    'runtime/vm': 'src/runtime/vm.ts',
    'runtime/worker-threads': 'src/runtime/worker-threads.ts',
    'runtime/crypto': 'src/runtime/crypto.ts',
    'runtime/zlib': 'src/runtime/zlib.ts',
  },
  format: ['esm'],
  splitting: false,
  dts: true,
  clean: true,
  banner: {
    js: "const require=globalThis.process?.getBuiltinModule?.('node:module').createRequire(import.meta.url);",
  },
  removeNodeProtocol: false,
  target: 'node20',
  // Filesystem entry points must share the constructors used to hydrate kernel results.
  external: ['vite', 'esbuild', './browser.js', './filesystem.js'],
  noExternal: ['@msgpack/msgpack', 'import-meta-resolve', 'process', 'ws'],
});
