import { defineConfig } from 'tsup';
export default defineConfig({
  entry: {
    vite: 'src/vite.ts',
    client: 'src/client.ts',
    browser: 'src/browser.ts',
    host: 'src/host.ts',
    worker: 'src/worker.ts',
    'run-worker': 'src/run-worker.ts',
    'instance-worker': 'src/instance-worker.ts',
    'runtime/assert-strict': 'src/runtime/assert-strict.ts',
    'runtime/async-hooks': 'src/runtime/async-hooks.ts',
    'runtime/child-process': 'src/runtime/child-process.ts',
    'runtime/constants': 'src/runtime/constants.ts',
    'runtime/dns': 'src/runtime/dns.ts',
    'runtime/fs': 'src/runtime/fs.ts',
    'runtime/fs-promises': 'src/runtime/fs-promises.ts',
    'runtime/filesystem': 'src/runtime/filesystem.ts',
    'runtime/http': 'src/runtime/http.ts',
    'runtime/http2': 'src/runtime/http2.ts',
    'runtime/https': 'src/runtime/https.ts',
    'runtime/module': 'src/runtime/module.ts',
    'runtime/socket-runtime': 'src/runtime/socket-runtime.ts',
    'runtime/net': 'src/runtime/net.ts',
    'runtime/path': 'src/runtime/path.ts',
    'runtime/os': 'src/runtime/os.ts',
    'runtime/perf-hooks': 'src/runtime/perf-hooks.ts',
    'runtime/process': 'src/runtime/process.ts',
    'runtime/readline': 'src/runtime/readline.ts',
    'runtime/sqlite': 'src/runtime/sqlite.ts',
    'runtime/stream-promises': 'src/runtime/stream-promises.ts',
    'runtime/timers': 'src/runtime/timers.ts',
    'runtime/tls': 'src/runtime/tls.ts',
    'runtime/tty': 'src/runtime/tty.ts',
    'runtime/url': 'src/runtime/url.ts',
    'runtime/util': 'src/runtime/util.ts',
    'runtime/v8': 'src/runtime/v8.ts',
    'runtime/vm': 'src/runtime/vm.ts',
    'runtime/worker-threads': 'src/runtime/worker-threads.ts',
    'runtime/crypto': 'src/runtime/crypto.ts',
    'runtime/zlib': 'src/runtime/zlib.ts',
  },
  format: ['esm'],
  splitting: false,
  dts: true,
  clean: true,
  banner: {
    js: "const require=globalThis.process?.getBuiltinModule?.('node:module').createRequire(import.meta.url);",
  },
  removeNodeProtocol: false,
  target: 'node20',
  // Runtime entry points share constructors across built-in imports and createRequire().
  external: [
    'vite',
    'esbuild',
    './browser.js',
    './filesystem.js',
    './socket-runtime.js',
    './tls.js',
    './http.js',
    './https.js',
  ],
  noExternal: ['@msgpack/msgpack', 'import-meta-resolve', 'ws'],
});
