import { defineConfig } from 'tsup';
export default defineConfig({
  entry: {
    index: 'src/index.ts',
    client: 'src/client.ts',
    access: 'src/access.ts',
    host: 'src/host.ts',
    worker: 'src/worker.ts',
    'runtime/fs-promises': 'src/runtime/fs-promises.ts',
    'runtime/http': 'src/runtime/http.ts',
    'runtime/http2': 'src/runtime/http2.ts',
    'runtime/https': 'src/runtime/https.ts',
    'runtime/module': 'src/runtime/module.ts',
    'runtime/net': 'src/runtime/net.ts',
    'runtime/process': 'src/runtime/process.ts',
    'runtime/stream-promises': 'src/runtime/stream-promises.ts',
    'runtime/timers': 'src/runtime/timers.ts',
    'runtime/tls': 'src/runtime/tls.ts',
    'runtime/crypto': 'src/runtime/crypto.ts',
    'runtime/zlib': 'src/runtime/zlib.ts',
  },
  format: ['esm'],
  splitting: false,
  dts: true,
  clean: true,
  target: 'node20',
  external: ['vite', 'esbuild', 'ws'],
  noExternal: ['@msgpack/msgpack', 'import-meta-resolve', 'process'],
});
